---
- name: enable/disable swap file include
  import_tasks: create_swap_file.yml
  when: base__create_swap_file
  tags: swap

- name: Load OS-Specific Tasks
  include_tasks: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution|lower }}.yml"
   - "os-{{ ansible_os_family|lower }}.yml"
   - "os-default.yml"
