---

- name: Install need system libraries and tools
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: latest
    pkg:
      - bash
      - build-essential
      - aptitude
      - openssl
      - rng-tools
      - libssl-dev
      - libssl-doc
      - libxml2-dev
      - libjpeg8
      - libjpeg8-dev
      - libfreetype6
      - libfreetype6-dev
      - zlib1g-dev
      - libpq-dev
      - libsqlite3-dev
  tags:
    - packages

- name: Install jpeg8
  apt:
    update_cache: "{{ update_apt_cache }}"
    force: yes
    state: installed
    pkg:
      - libjpeg-turbo8-dev
  ignore_errors: yes
  tags:
    - packages

- name: Install base packages
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: installed
    force: yes
    pkg:
      - curl
      - psmisc
      - htop
      - git
      - git-core
      - tig
      - mercurial
      - psmisc # pstree
      - lsof
      - iptables-persistent
  tags:
    - packages

- name: Install Python System-level packages
  apt:
    update_cache: "{{ update_apt_cache }}"
    force: yes
    state: installed
    pkg:
      - python-dev
      - python3-dev
      - python-pip
      - python3-pip
      - python-pycurl
      - python-virtualenv
      - python-setuptools
  tags:
    - packages
