---

- name: Install need system libraries and tools
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - build-essential
    - aptitude
    - openssl
    - rng-tools
    - libssl-dev
    - libssl-doc
    - libxml2-dev
    - libjpeg8
    - libjpeg8-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - libpq-dev
    - libsqlite3-dev

- name: Install jpeg8
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - libjpeg-turbo8-dev
  ignore_errors: yes

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - curl
    - psmisc
    - htop
    - git
    - git-core
    - tig
    - mercurial
    - psmisc # pstree
    - lsof
    - iptables-persistent

- name: Install Python System-level packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - python-dev
    - python3-dev
    - python-pip
    - python-pycurl
    - python-virtualenv
    - python-setuptools
