---
- name: Enabled Role
  debug: 
    msg: "Enabled {{ install_redis }}"

- name: enable/disable redis Ansible install
  import_tasks: base.yml
  when: install_redis|default(True)
  tags:
    - redis
