---
- name: Enabled Role
  debug: 
    msg: "Enabled {{ install_letsencrypt }}"

- name: enable/disable Letsencrypt Ansible install
  import_tasks: base.yml
  when: install_letsencrypt|default(True)
  tags:
    - letsencrypt
