---

- name: Add deps
  apt:
    name:
    state: present
    pkg:
      - apt-transport-https
      - ca-certificates

- name: Adding Certbot repository
  apt_repository:
      repo: "{{ letsencrypt__apt_repository }}"
      state: present
      update_cache: yes

- name: Ensure Cretbot packages are installed.
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: latest
    pkg:
      - certbot
