---

- name: Add deps
  apt:
    name: "{{ package_to_install }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
  loop_control:
    loop_var: package_to_install

- name: Adding Certbot repository
  apt_repository:
      repo: "{{ letsencrypt__apt_repository }}"
      state: present
      update_cache: yes

- name: Ensure Cretbot packages are installed.
  apt: name={{ package_to_install }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - certbot
  loop_control:
    loop_var: package_to_install
