---

- set_fact:
    sites__virtualenv_dir_version="{{virtualenvs_dir}}{{site_name}}-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

- name: Creates sites directory
  file:
    path: "{{ sites__site_dir }}"
    state: directory
    owner: "{{ sites__site_user }}"
    group: "{{ sites__shared_group }}"
    mode: 2775

- name: Creates sites bin directory
  file:
    path: "{{ sites__bin_dir }}"
    state: directory
    owner: "{{ sites__site_user }}"
    group: "{{ sites__shared_group }}"
    mode: 2775

- name: Creates log directory
  file:
    path: "{{ sites__site_log_dir }}"
    state: directory
    owner: "{{ sites__site_user }}"
    group: "{{ sites__shared_group }}"
    mode: 2775

- name: Creates run directory
  file:
    path: "{{ sites__site_run_dir }}"
    state: directory
    owner: "{{ sites__site_user }}"
    group: "{{ sites__shared_group }}"
    mode: 2775

- include: setup_virtualenv.yml
  tags:
    - virtualenv

- include: setup_project.yml
  tags:
    - project

- name: Copy the venv script
  template:
    src: venv.j2
    dest: "{{sites__sites_bin_dir}}venv"
    owner: root
    group: root
    mode: "u=rwx,g=rwx,o=rx"

- name: Fix ownership
  file:
    path: "{{ sites__site_dir }}"
    owner: "{{ sites__site_user }}"
    group: "{{ sites__shared_group }}"
    recurse: "yes"

- name: add venv to default bashrc
  lineinfile:
    dest: /etc/bash.bashrc
    line: "source {{sites__sites_bin_dir}}venv"
