---
- name: Enabled Role
  debug:
    msg: "Enabled {{ install_timezone }}"

- name: enable/disable timezone Ansible install
  import_tasks: base.yml
  when: install_timezone|default(True)
  tags:
    - timezone
