---

- name: Install supervisor
  yum:
    state: latest
    name:
      - supervisor
  tags:
    - packages

- name: install supervisor systemd unit file
  template:
    src: systemd-supervisor.service.j2
    dest: /etc/systemd/system/supervisor.service
    owner: root
    group: root
    mode: 0644
