---
- name: Install base packages
  yum:
    state: latest
    name:
      - ntp
      - ntpdate
  tags:
    - packages

- name: Start NTPD
  service:
    name: ntpd
    state: started
    enabled: "{{ntp__enabled_on_startup}}"
