---
- name: Install base packages
  yum: name={{ package_to_install }} state=latest
  with_items:
    - ntp
    - ntpdate
  loop_control:
    loop_var: package_to_install

- name: Start NTPD
  service:
    name: ntpd
    state: started
    enabled: "{{ntp__enabled_on_startup}}"
