- name: ensure custom facts directory exists
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory

- name: install custom fact module for Postgres version
  template:
    src: postgres_version.sh.j2
    dest: /etc/ansible/facts.d/postgres_version.fact
    mode: 0755

- name: reload ansible_local
  setup:
     filter: ansible_local
