---

- name: Install Postgresql
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: latest
    pkg:
      - postgresql
      - postgresql-contrib
      - python-psycopg2
      - python3-psycopg2
  tags:
    - packages
    - debian-base
