---

- name: Ensure MySQL packages are installed.
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: latest
    pkg:
      - mysql-common
      - mysql-server
      - libmysqlclient-dev

- name: Python3 mysql dependency
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: latest
    pkg:
      - python3-dev
      - python3-pip
