---

- name: Install Postgis
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: latest
    pkg:
      - postgis
      - postgresql-{{postgres__version}}-postgis-{{postgis__version}}
      - postgresql-{{postgres__version}}-postgis-scripts
  tags:
    - packages
    - debian-base
